name: pulsedancenz
favicon: null
layout_spectrum: 0.49584
typography_spectrum: 0.466
title: 'Pulse Dance Studio: West Coast Swing in Auckland, New Zealand'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e2005c'
    - '#5f00a7'
    - '#ff42a9'
    - '#a74cc2'
  brandStrength: 1
  lightness: 0.613562
  saturation: 0.4923852
  rhythmicContrast: 1
purpose: []
